services:
  lightrag:
    container_name: lightrag
    image: ghcr.io/hkuds/lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/hkuds/lightrag:latest
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - /home/armin/aina_data:/app/data/aina_storage
      - /home/armin/aina_inputs:/app/data/inputs
      - /etc/app/gen-lang-client-0048669359-51774bfb1a77.json:/etc/app/gen-lang-client-0048669359-51774bfb1a77.json
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
